<a href="https://colab.research.google.com/github/shreyaagr2909/Machine-Learning/blob/master/Neutral_network_from_scratc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [61]:
import numpy as np
import random

def sigmoid(x):
  return 1/(1 + np.exp(-x))

def sigmoid_derivative(x):
  return x * (1 - x)

training_inputs = np.array([[0,0,1],
                            [1,1,1],
                            [1,0,1],
                            [0,1,1]])

actual_outputs = np.array([[0,1,1,0]]).T

np.random.seed(1)
random_weigths = 2 * np.random.random((3,1))-1

for i in range(10000):
  input_layer = training_inputs
  predicted_output = sigmoid(np.dot(input_layer,random_weigths))
  error = actual_outputs - predicted_output
  adjustments = error * sigmoid_derivative(predicted_output)
  random_weigths = random_weigths + np.dot(input_layer.T , adjustments)

print("Error")
print(error)
print("Random weights")
print(random_weigths)
print("Predicted outputs")
print(predicted_output)


Error
[[-0.00966449]
 [ 0.00788043]
 [ 0.00641102]
 [-0.00786506]]
Random weights
[[ 9.67299303]
 [-0.2078435 ]
 [-4.62963669]]
Predicted outputs
[[0.00966449]
 [0.99211957]
 [0.99358898]
 [0.00786506]]
